/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author nem mèn mén
 */
public class trangChuFrame extends javax.swing.JFrame {

    /**
     * Creates new form trangChuFrame
     */
    public trangChuFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btlquanlysanpham1 = new javax.swing.JButton();
        btlquanlysanpham3 = new javax.swing.JButton();
        btlquanlysanpham2 = new javax.swing.JButton();
        btlquanlysanpham5 = new javax.swing.JButton();
        btlquanlysanpham4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 600));

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Zilla Slab SemiBold", 1, 24)); // NOI18N
        jLabel1.setText("SHOP COZY");

        btlquanlysanpham1.setText("Bán hàng");
        btlquanlysanpham1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btlquanlysanpham1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btlquanlysanpham1MouseClicked(evt);
            }
        });
        btlquanlysanpham1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlquanlysanpham1ActionPerformed(evt);
            }
        });

        btlquanlysanpham3.setText("Khách hàng");
        btlquanlysanpham3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btlquanlysanpham3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btlquanlysanpham3MouseClicked(evt);
            }
        });
        btlquanlysanpham3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlquanlysanpham3ActionPerformed(evt);
            }
        });

        btlquanlysanpham2.setText("Sản phẩm");
        btlquanlysanpham2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btlquanlysanpham2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btlquanlysanpham2MouseClicked(evt);
            }
        });
        btlquanlysanpham2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlquanlysanpham2ActionPerformed(evt);
            }
        });

        btlquanlysanpham5.setText("Tài khoản");
        btlquanlysanpham5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btlquanlysanpham5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btlquanlysanpham5MouseClicked(evt);
            }
        });
        btlquanlysanpham5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlquanlysanpham5ActionPerformed(evt);
            }
        });

        btlquanlysanpham4.setText("Thống kê");
        btlquanlysanpham4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btlquanlysanpham4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btlquanlysanpham4MouseClicked(evt);
            }
        });
        btlquanlysanpham4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlquanlysanpham4ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 0, 30));
        jButton2.setText("Đăng xuất");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Ảnh chụp màn hình 2025-10-04 073903.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btlquanlysanpham1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btlquanlysanpham3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btlquanlysanpham2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btlquanlysanpham5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btlquanlysanpham4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)))
                .addComponent(btlquanlysanpham1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btlquanlysanpham3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btlquanlysanpham2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btlquanlysanpham5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btlquanlysanpham4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btlquanlysanpham1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btlquanlysanpham1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btlquanlysanpham1MouseClicked

    private void btlquanlysanpham1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlquanlysanpham1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btlquanlysanpham1ActionPerformed

    private void btlquanlysanpham2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btlquanlysanpham2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btlquanlysanpham2MouseClicked

    private void btlquanlysanpham2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlquanlysanpham2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btlquanlysanpham2ActionPerformed

    private void btlquanlysanpham3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btlquanlysanpham3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btlquanlysanpham3MouseClicked

    private void btlquanlysanpham3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlquanlysanpham3ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btlquanlysanpham3ActionPerformed

    private void btlquanlysanpham4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btlquanlysanpham4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btlquanlysanpham4MouseClicked

    private void btlquanlysanpham4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlquanlysanpham4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btlquanlysanpham4ActionPerformed

    private void btlquanlysanpham5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btlquanlysanpham5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btlquanlysanpham5MouseClicked

    private void btlquanlysanpham5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlquanlysanpham5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btlquanlysanpham5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(trangChuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(trangChuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(trangChuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(trangChuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new trangChuFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btlquanlysanpham1;
    private javax.swing.JButton btlquanlysanpham2;
    private javax.swing.JButton btlquanlysanpham3;
    private javax.swing.JButton btlquanlysanpham4;
    private javax.swing.JButton btlquanlysanpham5;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
