/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;


import javax.swing.JPanel;

/**
 *
 * @author nem mèn mén
 */
public class trangChuFrame extends javax.swing.JFrame {

    /**
     * Creates new form trangChuFrame
     */
    public trangChuFrame() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
     
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btlquanlysanpham1 = new javax.swing.JButton();
        btlquanlysanpham3 = new javax.swing.JButton();
        btlquanlysanpham2 = new javax.swing.JButton();
        btlquanlysanpham5 = new javax.swing.JButton();
        btlquanlysanpham4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btlquanlysanpham6 = new javax.swing.JButton();
        pnlMain = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Zilla Slab SemiBold", 1, 24)); // NOI18N
        jLabel1.setText("SHOP COZY");

        btlquanlysanpham1.setText("Bán hàng");
        btlquanlysanpham1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btlquanlysanpham1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btlquanlysanpham1MouseClicked(evt);
            }
        });
        btlquanlysanpham1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlquanlysanpham1ActionPerformed(evt);
            }
        });

        btlquanlysanpham3.setText("Khách hàng");
        btlquanlysanpham3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btlquanlysanpham3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btlquanlysanpham3MouseClicked(evt);
            }
        });
        btlquanlysanpham3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlquanlysanpham3ActionPerformed(evt);
            }
        });

        btlquanlysanpham2.setText("Sản phẩm");
        btlquanlysanpham2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btlquanlysanpham2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btlquanlysanpham2MouseClicked(evt);
            }
        });
        btlquanlysanpham2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlquanlysanpham2ActionPerformed(evt);
            }
        });

        btlquanlysanpham5.setText("Hoá đơn");
        btlquanlysanpham5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btlquanlysanpham5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btlquanlysanpham5MouseClicked(evt);
            }
        });
        btlquanlysanpham5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlquanlysanpham5ActionPerformed(evt);
            }
        });

        btlquanlysanpham4.setText("Thống kê");
        btlquanlysanpham4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btlquanlysanpham4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btlquanlysanpham4MouseClicked(evt);
            }
        });
        btlquanlysanpham4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlquanlysanpham4ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(30, 30, 30));
        jButton2.setText("Đăng xuất");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Ảnh chụp màn hình 2025-10-04 073903.png"))); // NOI18N

        btlquanlysanpham6.setText("Tài khoản");
        btlquanlysanpham6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btlquanlysanpham6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btlquanlysanpham6MouseClicked(evt);
            }
        });
        btlquanlysanpham6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlquanlysanpham6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btlquanlysanpham1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btlquanlysanpham3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btlquanlysanpham2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btlquanlysanpham4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btlquanlysanpham5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btlquanlysanpham6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addComponent(btlquanlysanpham1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btlquanlysanpham3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btlquanlysanpham2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btlquanlysanpham5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btlquanlysanpham6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btlquanlysanpham4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pnlMain.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));
        pnlMain.setLayout(new java.awt.BorderLayout());
        pnlMain.add(jLabel5, java.awt.BorderLayout.LINE_END);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/vn-11134210-7r98o-llomssp1oqu70e_1.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 765, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(327, 327, 327)
                    .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(782, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btlquanlysanpham1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btlquanlysanpham1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btlquanlysanpham1MouseClicked

    private void btlquanlysanpham1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlquanlysanpham1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btlquanlysanpham1ActionPerformed

    private void btlquanlysanpham2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btlquanlysanpham2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btlquanlysanpham2MouseClicked

    private void btlquanlysanpham2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlquanlysanpham2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btlquanlysanpham2ActionPerformed

    private void btlquanlysanpham3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btlquanlysanpham3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btlquanlysanpham3MouseClicked

    private void btlquanlysanpham3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlquanlysanpham3ActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_btlquanlysanpham3ActionPerformed

    private void btlquanlysanpham4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btlquanlysanpham4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btlquanlysanpham4MouseClicked

    private void btlquanlysanpham4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlquanlysanpham4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btlquanlysanpham4ActionPerformed

    private void btlquanlysanpham5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btlquanlysanpham5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btlquanlysanpham5MouseClicked

    private void btlquanlysanpham5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlquanlysanpham5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btlquanlysanpham5ActionPerformed

    private void btlquanlysanpham6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btlquanlysanpham6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btlquanlysanpham6MouseClicked

    private void btlquanlysanpham6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlquanlysanpham6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btlquanlysanpham6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(trangChuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(trangChuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(trangChuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(trangChuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new trangChuFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btlquanlysanpham1;
    private javax.swing.JButton btlquanlysanpham2;
    private javax.swing.JButton btlquanlysanpham3;
    private javax.swing.JButton btlquanlysanpham4;
    private javax.swing.JButton btlquanlysanpham5;
    private javax.swing.JButton btlquanlysanpham6;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel pnlMain;
    // End of variables declaration//GEN-END:variables
}
